services:
  sftp:
    image: atmoz/sftp:latest
    container_name: balancing-sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp/upload:/home/testuser/filesToProcess
      - ./sftp/archive:/home/testuser/archive
      - ./sftp/error:/home/testuser/error
    command: testuser:testpass:1001
