spring.application.name=tscnet-daily-process
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/tscnet_daily_process
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Production requirement: 00:01 every day.
# 0 * * * * * (every minute).
app.scheduler.cron=0 1 0 * * *
app.scheduler.enabled=true

# Europe/Munich is used as the process timezone assumption.
app.scheduler.zone=Europe/Munich

app.simulate.failure=false

sftp.host=localhost
sftp.port=2222
sftp.user=testuser
sftp.password=testpass

procurement.assessment.minimum-quantity=10
procurement.assessment.maximum-weighted-average-price=1000
procurement.assessment.minimum-offers=1

# Kafka Bootstrap Server Address
spring.kafka.bootstrap-servers=localhost:9092

# Producer Serialization Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional Producer Performance Tuning
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

