spring.application.name=spring-ai-rag-tutorial

spring.datasource.url=jdbc:postgresql://localhost:5433/vectordb
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.springframework.ai.vectorstore=DEBUG

chat.api.key=your-api-key
chat.model.name=gemini-3.6-flash